import type { ForceData, SectorData, Threat } from "@/lib/types";

export const SOURCE_STALE_AFTER_MS = 15 * 60 * 1000;

const NOW_MS = Date.now();
function createdAtForMomentum(momentum: Threat["momentum"]): number {
  const hourMs = 60 * 60 * 1000;
  // Escalating/peaking threats should be recent — decay should be minimal vs fading seeds.
  if (momentum === "escalating") return NOW_MS - 3 * hourMs;
  if (momentum === "peaking") return NOW_MS - 6 * hourMs;
  if (momentum === "fading") return NOW_MS - 60 * hourMs;
  return NOW_MS - 24 * hourMs;
}

export const CATEGORY_WEIGHTS = {
  geopolitical: 0.35,
  macroeconomic: 0.25,
  sentiment: 0.2,
  supplyChain: 0.12,
  climate: 0.08,
};

export const TICKERS = [
  { sym: "SPY", price: 568.42, chg: -0.73 },
  { sym: "QQQ", price: 487.15, chg: -1.12 },
  { sym: "BTC", price: 87241, chg: 2.34 },
  { sym: "ETH", price: 3412, chg: 1.87 },
  { sym: "GLD", price: 243.67, chg: 0.95 },
  { sym: "CL", price: 71.23, chg: -1.54 },
  { sym: "TSLA", price: 178.9, chg: -2.41 },
  { sym: "NVDA", price: 124.56, chg: -1.89 },
];

export const SECTORS: SectorData[] = [
  { name: "Technology", score: 74, count: 3 },
  { name: "Energy", score: 58, count: 2 },
  { name: "Finance", score: 61, count: 1 },
  { name: "Crypto", score: 52, count: 2 },
  { name: "Defense", score: 41, count: 1 },
  { name: "Commodities", score: 47, count: 1 },
];

export const FORCES: ForceData[] = [
  { name: "Geopolitical", weight: 0.35, score: 72 },
  { name: "Macro", weight: 0.25, score: 61 },
  { name: "Sentiment", weight: 0.2, score: 48 },
  { name: "Supply Chain", weight: 0.12, score: 55 },
  { name: "Climate", weight: 0.08, score: 47 },
];

export const THREATS: Threat[] = [
  {
    id: 1,
    title: "Taiwan Strait Military Escalation",
    category: "Geopolitical",
    severity: "critical",
    createdAt: createdAtForMomentum("escalating"),
    assets: ["NVDA", "TSM", "AAPL", "QQQ"],
    direction: "bearish",
    probability: 0.23,
    probSource: "Polymarket",
    probDelta: 0.08,
    confidence: "medium",
    volume: 84200,
    cascadeEta: "2-5 days",
    momentum: "escalating",
    summary: "PLA naval drills expanded near Taiwan; semiconductor supply chain risk elevated.",
    sector: "Technology",
    verified: true,
    sourceCount: 4,
    probHistory: [0.12, 0.14, 0.15, 0.18, 0.19, 0.21, 0.23],
  },
  {
    id: 2,
    title: "Federal Reserve Emergency Rate Decision",
    category: "Macroeconomic",
    severity: "high",
    createdAt: createdAtForMomentum("escalating"),
    assets: ["SPY", "QQQ", "TLT", "DXY"],
    direction: "bearish",
    probability: 0.41,
    probSource: "Kalshi",
    probDelta: 0.12,
    confidence: "high",
    volume: 312000,
    cascadeEta: "3-7 days",
    momentum: "escalating",
    summary: "Hot CPI print has increased emergency rate decision odds; yield curve inverting.",
    sector: "Finance",
    verified: true,
    sourceCount: 7,
    probHistory: [0.22, 0.25, 0.29, 0.31, 0.35, 0.38, 0.41],
  },
  {
    id: 3,
    title: "EU Comprehensive Crypto Regulation",
    category: "Regulatory",
    severity: "high",
    createdAt: createdAtForMomentum("peaking"),
    assets: ["BTC", "ETH", "COIN", "MSTR"],
    direction: "bearish",
    probability: 0.67,
    probSource: "Polymarket",
    probDelta: -0.03,
    confidence: "high",
    volume: 156000,
    cascadeEta: "1-3 weeks",
    momentum: "peaking",
    summary: "EU regulatory timeline accelerated; stronger reserve requirements imminent.",
    sector: "Crypto",
    verified: true,
    sourceCount: 5,
    probHistory: [0.58, 0.62, 0.65, 0.68, 0.7, 0.69, 0.67],
  },
  {
    id: 4,
    title: "Gulf of Aden Shipping Route Disruption",
    category: "Supply Chain",
    severity: "medium",
    createdAt: createdAtForMomentum("fading"),
    assets: ["CL", "XLE", "FDX"],
    direction: "bearish",
    probability: 0.78,
    probSource: "Polymarket",
    probDelta: 0.02,
    confidence: "medium",
    volume: 45000,
    cascadeEta: "1-4 weeks",
    momentum: "fading",
    summary: "Houthi attacks disrupting Red Sea trade lanes; tanker insurance premiums surging.",
    sector: "Energy",
    verified: true,
    sourceCount: 3,
    probHistory: [0.71, 0.74, 0.76, 0.79, 0.8, 0.79, 0.78],
  },
  {
    id: 5,
    title: "US-China Semiconductor Export Controls",
    category: "Regulatory",
    severity: "high",
    createdAt: createdAtForMomentum("escalating"),
    assets: ["NVDA", "AMD", "ASML", "LRCX"],
    direction: "bearish",
    probability: 0.54,
    probSource: "Kalshi",
    probDelta: 0.06,
    confidence: "high",
    volume: 223000,
    cascadeEta: "1-2 weeks",
    momentum: "escalating",
    summary: "BIS expanding export control list to cover advanced AI accelerators; Dutch ASML under pressure.",
    sector: "Technology",
    verified: true,
    sourceCount: 6,
    probHistory: [0.38, 0.41, 0.44, 0.47, 0.5, 0.52, 0.54],
  },
  {
    id: 6,
    title: "Category 5 Hurricane Approaching Gulf Coast",
    category: "Climate",
    severity: "medium",
    createdAt: createdAtForMomentum("escalating"),
    assets: ["CL", "NG", "XLE", "CORN"],
    direction: "bearish",
    probability: 0.89,
    probSource: "Kalshi",
    probDelta: 0.15,
    confidence: "high",
    volume: 187000,
    cascadeEta: "2-6 weeks",
    momentum: "escalating",
    summary: "Rapid intensification over Gulf; offshore rig evacuations underway, refinery shutdowns expected.",
    sector: "Commodities",
    verified: true,
    sourceCount: 8,
    probHistory: [0.45, 0.55, 0.67, 0.74, 0.81, 0.86, 0.89],
  },
  {
    id: 7,
    title: "Bitcoin ETF Institutional Rotation Signal",
    category: "Sentiment",
    severity: "low",
    createdAt: createdAtForMomentum("fading"),
    assets: ["BTC", "IBIT", "GBTC"],
    direction: "bullish",
    probability: 0.33,
    probSource: "Polymarket",
    probDelta: -0.05,
    confidence: "low",
    volume: 8200,
    cascadeEta: "1-3 days",
    momentum: "fading",
    summary: "Unconfirmed reports of large sovereign wealth fund allocating to spot BTC ETFs.",
    sector: "Crypto",
    verified: false,
    sourceCount: 1,
    probHistory: [0.41, 0.39, 0.38, 0.36, 0.35, 0.34, 0.33],
  },
  {
    id: 8,
    title: "Russian Energy Infrastructure Sanctions",
    category: "Geopolitical",
    severity: "medium",
    createdAt: createdAtForMomentum("escalating"),
    assets: ["CL", "NG", "XLE"],
    direction: "bearish",
    probability: 0.46,
    probSource: "Polymarket",
    probDelta: 0.04,
    confidence: "medium",
    volume: 67000,
    cascadeEta: "1-3 weeks",
    momentum: "escalating",
    summary: "G7 considering secondary sanctions on Russian pipeline infrastructure operators.",
    sector: "Energy",
    verified: true,
    sourceCount: 3,
    probHistory: [0.35, 0.37, 0.39, 0.41, 0.43, 0.44, 0.46],
  },
  {
    id: 9,
    title: "NVIDIA Antitrust Investigation Expansion",
    category: "Regulatory",
    severity: "medium",
    createdAt: createdAtForMomentum("peaking"),
    assets: ["NVDA", "AMD", "INTC"],
    direction: "bearish",
    probability: 0.38,
    probSource: "Kalshi",
    probDelta: 0.02,
    confidence: "medium",
    volume: 52000,
    cascadeEta: "2-8 weeks",
    momentum: "peaking",
    summary: "DOJ expanding CUDA ecosystem probe to cover data center pricing and bundling practices.",
    sector: "Technology",
    verified: true,
    sourceCount: 2,
    probHistory: [0.31, 0.33, 0.34, 0.36, 0.37, 0.38, 0.38],
  },
];
